name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: go get ./cmd/dlive-dl

      - name: Build
        run: go build -v ./cmd/dlive-dl

      - name: Upload Artifact (Unix)
        uses: actions/upload-artifact@v2
        if: "matrix.os != 'windows'"
        with:
          name: dlive-dl-${{ matrix.os }}
          path: ./dlive-dl

      - name: Upload Artifact (Windows)
        uses: actions/upload-artifact@v2
        if: "matrix.os == 'windows'"
        with:
          name: dlive-dl-${{ matrix.os }}
          path: dlive-dl.exe